-- ============================================================================
-- SUPERSEDED FILE — DO NOT RUN
-- ============================================================================
-- This file previously added a grade-level "track" column and made age
-- optional. That approach has been replaced by a proper independent
-- school_type dimension on subject_grades / teacher_subjects / lesson_slots
-- / reservations (grades are now shared across both school types).
--
-- If you are setting up fresh: schema.sql + functions.sql already include
-- everything correctly. You do not need this file at all.
--
-- If you have an existing database from before the school_type change:
-- run supabase/rebuild-schema.sql, then re-run schema.sql and functions.sql.
-- ============================================================================
